CREATE TABLE `api`.`productos` 
(`ID_PRODUCTO` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
`name` VARCHAR(30) NOT NULL ,
`descripcion` VARCHAR(30) NOT NULL ,
`stock` INT(10) NOT NULL ,
`url` VARCHAR(200) NOT NULL , 
`imageName` VARCHAR(100) NOT NULL ,
`IDToken` VARCHAR(150) NOT NULL ,
PRIMARY KEY (`ID_PRODUCTO`)
) ENGINE = InnoDB;